dsp: platform: Fix overlooked call to PLDM_MSGBUF_DEFINE_P()
In context, this should now be PLDM_MSGBUF_RW_DEFINE_P() for
const-correctness.

Fixes:

```
../src/dsp/platform.c:3550:2: error: call to undeclared function 'PLDM_MSGBUF_DEFINE_P'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3550 |         PLDM_MSGBUF_DEFINE_P(buf);
      |         ^
```

Fixes: 7a8d932bc3cd ("msgbuf: Define a separate msgbuf structure for encode/decode function")
Change-Id: I448395b6bc1f4914ca01f3edfd8c3cf7ce60a7d9
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>