tests: dsp: firmware_update: Drop guards for package parsing tests
These are now marked stable and shouldn't be conditionally compiled.

Fixes:

```
../tests/dsp/firmware_update.cpp:53:5: error: unused variable 'PLDM_FWUP_PACKAGE_HEADER_IDENTIFIER_V1_1' [-Werror,-Wunused-const-variable]
   53 |     PLDM_FWUP_PACKAGE_HEADER_IDENTIFIER_V1_1{
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../tests/dsp/firmware_update.cpp:59:5: error: unused variable 'PLDM_FWUP_PACKAGE_HEADER_IDENTIFIER_V1_2' [-Werror,-Wunused-const-variable]
   59 |     PLDM_FWUP_PACKAGE_HEADER_IDENTIFIER_V1_2{0x31, 0x19, 0xce, 0x2f, 0xe8, 0x0a,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../tests/dsp/firmware_update.cpp:64:5: error: unused variable 'PLDM_FWUP_PACKAGE_HEADER_IDENTIFIER_V1_3' [-Werror,-Wunused-const-variable]
   64 |     PLDM_FWUP_PACKAGE_HEADER_IDENTIFIER_V1_3{0x7b, 0x29, 0x1c, 0x99, 0x6d, 0xb6,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Fixes: f6ef78f676a9 ("dsp: firmware_update: Stabilized new firmware package parsing ABI")
Change-Id: I3386d3827b80d31cb702cb9f3f67d616b09be478
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>