fix config HAVE_STRUCT_MCTP_FQ_ADDR
The symbol was not defined in config.h in my build configuration,
resulting in following build failure:

```
../src/transport/af-mctp.c:38:8: error: redefinition of ‘struct mctp_fq_addr’
   38 | struct mctp_fq_addr {
      |        ^~~~~~~~~~~~
In file included from ../src/transport/af-mctp.c:17:
/usr/include/linux/mctp.h:43:8: note: originally defined here
   43 | struct mctp_fq_addr {
      |        ^~~~~~~~~~~~
```

It seems like meson does not emit things from the configuration data
unless there is a template like #mesondefine or similar in the
config.h.in file.

Put a `#mesondefine` in the config.h.in to emit it.

References:
[1] https://mesonbuild.com/Configuration.html

Fixes: d39dd22206f1 ("meson: Rework ABI control macros to also enable API control")
Change-Id: I33c9f779ec16b4d4bb1208c7606b3fa4222c9d2d
Signed-off-by: Alexander Hansen <alexander.hansen@9elements.com>