dsp: bios_table: Rename pldm_bios_table_attr_entry_string_decode_def_string_length_check()
Introduce
pldm_bios_table_attr_entry_string_decode_def_string_length(), deprecate
pldm_bios_table_attr_entry_string_decode_def_string_length_check(), add
the rename configuration and apply it.

As a consequence clang-tidy detected the following, though it's unclear
why it was not detected previously:

```
clang-tidy-17 -export-fixes /tmp/tmpf4lalo2j/tmpkiyu1sgy.yaml -p=/home/andrew/src/openbmc.org/openbmc/libpldm/origin/build1qcxy8ww -quiet /home/andrew/src/openbmc.org/openbmc/libpldm/origin/src/dsp/bios_table.c
../src/dsp/bios_table.c:460:2: error: Null pointer passed to 2nd parameter expecting 'nonnull' [clang-analyzer-core.NonNullParamChecker,-warnings-as-errors]
  460 |         memcpy(buffer, fields->def_string, length);
      |         ^              ~~~~~~~~~~~~~~~~~~
../src/dsp/bios_table.c:457:11: note: Assuming the condition is true
  457 |         length = length < (size - 1) ? length : (size - 1);
      |                  ^~~~~~~~~~~~~~~~~~~
../src/dsp/bios_table.c:457:11: note: '?' condition is true
../src/dsp/bios_table.c:460:2: note: Null pointer passed to 2nd parameter expecting 'nonnull'
  460 |         memcpy(buffer, fields->def_string, length);
      |         ^              ~~~~~~~~~~~~~~~~~~
```

gitlint-ignore: T1, B1
Change-Id: Ic390e00f520cb3d5e479604b34939cefd09e9448
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>