scripts/pre-submit: rm test build w/o test symbols
To properly test libpldm functions which are not part of stable ABI,
remove the build configuration for tests which does not link them.

Did this change to prevent link failure like below:

```
/usr/bin/ld: tests/bindings/cpp/firmware_update_test.p/firmware_update_test.cpp.o: in function `PackageParser_InvalidPkgBadChecksum_Test::TestBody()':
/home/alexander/upstreaming/libpldm/tmp.iWoH86G8hy/../tests/bindings/cpp/firmware_update_test.cpp:356:(.text+0x41db): undefined reference to `pldm::fw_update::PackageParser::parse(std::vector<unsigned char, std::allocator<unsigned char> > const&, pldm_package_format_pin&)'
collect2: error: ld returned 1 exit status
```

Change-Id: I6d7a4001d810cc16ef93304f900a992383818e7e
Signed-off-by: Alexander Hansen <alexander.hansen@9elements.com>